# Assignment-6

Name: Anish kumar

Regd. no: 2241011101

Section: 2241007

 1. Convert the list [’100’, ’200’, ’python’, ’300.12’, ’400’] to a Series object than sort it. The output should be [’100’,’200’,’300.12’,’400’,’python’].

In [2]:
import pandas as pd
l=['100','200','python','300.12','400']
arr=pd.Series(l)
print(arr,'\n')
print('sorted data:')
arr.sort_values()

0       100
1       200
2    python
3    300.12
4       400
dtype: object 

sorted data:


0       100
1       200
3    300.12
4       400
2    python
dtype: object

 2. Write a Pandas program to convert the first column of a DataFrame as a Series.

In [12]:
data={'c1':[1,2,3,4,5,6],
'c2':['A','B','C','D','E','F']}
df=pd.DataFrame(data)
firstColoumSeries=df.iloc[:,0]
print("Original DataFrame:")
print(df)
print("\nFirst Column as Series:")
print(firstColoumSeries)

Original DataFrame:
   c1 c2
0   1  A
1   2  B
2   3  C
3   4  D
4   5  E
5   6  F

First Column as Series:
0    1
1    2
2    3
3    4
4    5
5    6
Name: c1, dtype: int64


 3. Create a data frame containing names of first five presidents of India,and years served by them.Once the data frame is created, add another column containing their home state for the first four presidents.

In [14]:
data={'Name':['Rajendra Prasad','Sarvepalli Radhakrishnan','Zakir Hussain','Varahagiri Venkata Giri','Fakhruddin Ali Ahmed'],
        'Years Served':['1950-1962','1962-1967','1967-1969','1969-1974','1974-1977']} 
df=pd.DataFrame(data)
df

Name Years Served
0           Rajendra Prasad    1950-1962
1  Sarvepalli Radhakrishnan    1962-1967
2             Zakir Hussain    1967-1969
3   Varahagiri Venkata Giri    1969-1974
4      Fakhruddin Ali Ahmed    1974-1977

In [15]:
df['Home State']=['Bihar', 'Andhra Pradesh', 'Bihar', 'Kerala', None]
df

Name Years Served      Home State
0           Rajendra Prasad    1950-1962           Bihar
1  Sarvepalli Radhakrishnan    1962-1967  Andhra Pradesh
2             Zakir Hussain    1967-1969           Bihar
3   Varahagiri Venkata Giri    1969-1974          Kerala
4      Fakhruddin Ali Ahmed    1974-1977            None

 4. Convert s1=[1,2,3,4,2] and s2=[3,4,5,6] to two series objects. Find elements in s1, which are not
 present in s2.

In [25]:
s1=[1,2,3,4,2]
s2=[3,4,5,6]

S1=pd.Series(s1)
print(S1)

S2=pd.Series(s2)
print(S2)

print("element that are not present in s1:")
for i in s1:
    if i not in s2:
        print(i)

0    1
1    2
2    3
3    4
4    2
dtype: int64
0    3
1    4
2    5
3    6
dtype: int64
element that are not present in s1:
1
2
2


 5. Write a Pandas program to find the index of the first occurrence of the smallest and largest value of a
 given series. If the input is [1,1,3,7,88,12,88,23,3,1,9,0], the output should be 0 and 4.

In [18]:
x=[1,1,3,7,88,12,88,23,3,1,9,0]
s=pd.Series(x)
print(s)
print("Index of the first occurrence of the smallest and largest value of the series:")
print("smallest:",s.idxmin())
print("largest:",s.idxmax())

0      1
1      1
2      3
3      7
4     88
5     12
6     88
7     23
8      3
9      1
10     9
11     0
dtype: int64
Index of the first occurrence of the smallest and largest value of the series:
smallest: 11
largest: 4


 6. Convert L=[’Cry’, ’Apple’, ’Orange’, ’Sky’, ’Banana’] to a pandas series.Create a new series with
 the elements which has a vowel. Create another series which starts with a vowel.

In [20]:
import pandas as pd
L=['Cry','Apple','Orange','Sky','Banana']
s=pd.Series(L)

# Create a series with elements containing vowels
s1=s[s.str.contains('[aeiouAEIOU]')]

# Create a series with elements starting with a vowel
s2=s[s.str[0].str.lower().isin(['a', 'e', 'i', 'o', 'u'])]

print("Original Series:")
print(s)

print("\nSeries with Elements Containing Vowels:")
print(s1)

print("\nSeries with Elements Starting with a Vowel:")
print(s2)


Original Series:
0       Cry
1     Apple
2    Orange
3       Sky
4    Banana
dtype: object

Series with Elements Containing Vowels:
1     Apple
2    Orange
4    Banana
dtype: object

Series with Elements Starting with a Vowel:
1     Apple
2    Orange
dtype: object


 7. Write a Pandas program to calculate the number of characters in each word in a given series.

In [21]:
import pandas as pd
L=['Cry','Apple','Orange','Sky','Banana']
s=pd.Series(L)
l=s.str.len()
df=pd.DataFrame({'Word':s,'Length':l})
df

Word  Length
0     Cry       3
1   Apple       5
2  Orange       6
3     Sky       3
4  Banana       6

 8. Create a 4*4 data frame where each entry is from the standard normal distribution. Create another matrix which is element wise square root of the previous matrix. Find the number of NaN values in
 each column. Find the mean and standard deviation of each column.

In [5]:
import numpy as np
import pandas as pd

# Generate a 4x4 matrix with entries from the standard normal distribution
matrix=np.random.standard_normal((4, 4))

# Calculate the element-wise square root of the matrix
squareRootMatrix=np.sqrt(matrix)

# Create a data frame from the matrix
df=pd.DataFrame(squareRootMatrix)

# Calculate the number of NaN values, mean, and standard deviation for each column
nanCounts=df.isna().sum()
means=df.mean()
stdDevs=df.std()

# Print the results
print("Matrix:")
print(matrix)
print("\nSquare Root Matrix:")
print(squareRootMatrix)
print("Data Frame:")
print(df)
print("\nNaN Counts:")
print(nanCounts)
print("\nMeans:")
print(means)
print("\nStandard Deviations:")
print(stdDevs)

Matrix:
[[-1.94093588  0.4392883   0.12482826 -0.77149446]
 [-0.22507675  0.58095939 -0.14360922  2.33390816]
 [-0.39339114  2.17181742  1.64873922 -0.89536789]
 [-0.18902861 -0.40653364 -1.17542166 -1.74620026]]

Square Root Matrix:
[[       nan 0.66278828 0.35331044        nan]
 [       nan 0.76220692        nan 1.52771338]
 [       nan 1.47370873 1.2840324         nan]
 [       nan        nan        nan        nan]]
Data Frame:
    0         1         2         3
0 NaN  0.662788  0.353310       NaN
1 NaN  0.762207       NaN  1.527713
2 NaN  1.473709  1.284032       NaN
3 NaN       NaN       NaN       NaN

NaN Counts:
0    4
1    1
2    2
3    3
dtype: int64

Means:
0         NaN
1    0.966235
2    0.818671
3    1.527713
dtype: float64

Standard Deviations:
0         NaN
1    0.442288
2    0.658120
3         NaN
dtype: float64


C:\Users\anish\AppData\Local\Temp\ipykernel_1412\2900044679.py:8: RuntimeWarning: invalid value encountered in sqrt
  squareRootMatrix=np.sqrt(matrix)


9. Create a 4*4 matrix, where each row contains Student’s name,registration no,sec and cgpa.
 D=’Name’:[’A’,”B”,”C”,”D”], ’Regno’:[1,2,3,4], ’Sec’:[’i’,’ii’,’iii’,’iv’], ’CGPA’:[7,8,9,10] Find the name,
 registration no of the student with highest cgpa. (Use np.max on cgpa column) What is the row and
 column number of the cell with the highest CGPA?(Convert dataframe to numpy array and see which
 indices has maximum value)

In [79]:
import pandas as pd
D={'Name':['A','B','C','D'],
   'RedgdNo':[1,2,3,4],
   'sec':['i','ii','iii','iv'],
   'cgpa':[7,8,9,10]}

df=pd.DataFrame(D)
print('Data Frame:')
print(df)

# highestCGPA=df['cgpa'].max()
# x=df[df['cgpa']==highestCGPA][['Name','RedgdNo']]
# print(x)
print('the name, registration no of the student with highest cgpa:')
hcn=df[df['cgpa']==df['cgpa'].max()]['Name'].values[0]
print('Name:',hcn)

hcr=df[df['cgpa']==df['cgpa'].max()]['RedgdNo'].values[0]
print('Regd No:',hcr)

print('the row and column number of the cell with the highest CGPA:')
# highestCGPARow=df['cgpa'].idxmax()
# print('row:',highestCGPARow)
rc=np.where(df==df.max())
print(rc)

print('Use np.max on cgpa column:')
npdf=df.to_numpy()
print('Numpy array:')
print(npdf)
npdf[:,3].max()
# maxIndex=np.argmax(npdf)

Data Frame:
  Name  RedgdNo  sec  cgpa
0    A        1    i     7
1    B        2   ii     8
2    C        3  iii     9
3    D        4   iv    10
the name, registration no of the student with highest cgpa:
Name: D
Regd No: 4
the row and column number of the cell with the highest CGPA:
(array([3, 3, 3, 3], dtype=int64), array([0, 1, 2, 3], dtype=int64))
Use np.max on cgpa column:
Numpy array:
[['A' 1 'i' 7]
 ['B' 2 'ii' 8]
 ['C' 3 'iii' 9]
 ['D' 4 'iv' 10]]


10

10. Create a data frame object,df containing some Nan values. Count the number of missing values in
 each column of df. Which column has the maximum number of missing values?(create a function to
 count nan values in a column,use df.apply and that function)

In [88]:
data={'A':[1,2,3,np.nan,None],
    'B':[1.4,1.0,None,np.nan,np.nan],
    'C':[np.nan,np.nan,np.nan,1,None]}
df=pd.DataFrame(data)
missingValues=df.isnull().sum()
print('the number of missing values in each column:')
print(missingValues)
print('column has the maximum number of missing values:')
missingValues.idxmax()

the number of missing values in each column:
A    2
B    3
C    4
dtype: int64
column has the maximum number of missing values:


'C'

11. Create a 4*4 matrix, entries from np.arange(16). Reverse the entries of the matrix. The matrix will look like:

In [95]:
import numpy as np
x=np.arange(16).reshape(4,4)
r=np.flip(x)
r

array([[15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

12. Create a 4*4 matrix where each entries are from standard normal distribution. Add a column to this
 dataframe, which contains row wise minimums.

In [103]:
x=np.random.standard_normal((4, 4))
df=pd.DataFrame(x)
df['min']=np.min(df.values,axis=1) # axis=1; column
df

0         1         2         3       min
0  1.057167  0.642492 -0.280820 -0.658117 -0.658117
1  0.288150  1.767884  2.089377 -0.367981 -0.367981
2  0.907408 -2.035014 -0.470189  0.760535 -2.035014
3 -0.018235  0.343373  1.040429 -0.993466 -0.993466

13. Create a 4*4 matrix entries from standard normal distribution.Add another row where all entries are
 NaN. Replace missing values in ’col1’ and ’col2’ columns with the irrespective mean.

In [120]:
import numpy as np
import pandas as pd

# Create a 4x4 matrix with standard normal distribution
x=np.random.standard_normal((4,4))
df=pd.DataFrame(x, columns=['col1', 'col2', 'col3', 'col4'])

# Add a row of NaNs
df.loc[4] = np.nan

print('Before matrix:')
print(df)

# Calculate mean for 'col1' and 'col2'
meanCol1 = df['col1'].mean()
meanCol2 = df['col2'].mean()

# Replace missing values in 'col1' and 'col2' with the respective mean
df['col1'] = df['col1'].fillna(meanCol1)
df['col2'] = df['col2'].fillna(meanCol2)

print('After matrix:')
print(df)

Before matrix:
       col1      col2      col3      col4
0  0.783419 -1.418413  0.837519  0.308217
1  0.235522  0.146144 -0.172531  0.712967
2 -0.271967 -1.307944 -1.330137  0.806793
3  0.395483 -0.441588  1.318296  0.884651
4       NaN       NaN       NaN       NaN
After matrix:
       col1      col2      col3      col4
0  0.783419 -1.418413  0.837519  0.308217
1  0.235522  0.146144 -0.172531  0.712967
2 -0.271967 -1.307944 -1.330137  0.806793
3  0.395483 -0.441588  1.318296  0.884651
4  0.285614 -0.755450       NaN       NaN
